const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@subhasis4502";
const name = "Name";
const nameHint = "Subhasis Das";
const email = "Email";
const emailHint = "example@domain.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const forgetPass = "Forget Password";
const login = "Log In";
const logout = "Log Out";
const signup = "Sign Up";
const createNewAccount = "or, create a new account";
const haveAccount = "Already have an account? ";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms & Conditions";
const loggedin = "Logged in Successfully";
const loggedOut = "Logged out Successfully";

const home = "Home";
const categories = "Categories";
const cart = "Cart";
const account = "Account";

const searchAnything = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    featureCategories = "Feature Categories",
    featureProducts = "Feature Products",
    allProducts = "All Products",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    suits = "Suits",
    tShirts = "T-Shirts",
    girlsDress = "Girls Dresses",
    menClothingFashion = "Men Clothing & Fashion",
    jewelery = "Jewelery & Ornaments",
    kidfashion = "Kid Fashion",
    sportswear = "Sportswear",
    makup = "Make Up",
    eyewears = "Glasses and Eyewears",
    accesories = "Accesories",
    shoes = "Sneakers & Shoes";
